=== gitmala/AnyRestDotNet/AnyRest/ConfigSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {

    "HTTPMethod": {
      "type": "string",
      "enum":  [ "get", "put", "post", "update", "delete" ]
    },

    "ParameterType": {
      "type": "string",
      "enum":  [ "string", "int", "double", "bool" ]
    },

    "QueryParameter" : {
      "type": "object",
      "properties": {
        "Name": { "type": "string" },
        "Type": { "$ref": "#/definitions/ParameterType" },
        "Optional": { "type": "boolean" }
        },
        "required": ["Name"]
    }
  },

  "type": "object",
  "properties": {

    "test": {"$ref": "#/definitions/QueryParameter"},

    "EndPointDefaults": {
      "type": "object",
      "properties": {
        "RoutePrefix": {
          "type": "string",
          "default": ""
        },
        "Route": {
          "type": "string",
          "default": ""
        }
      },
      "required": []
    },

    "ActionDefaults": {
      "type": "object",
      "properties": {
        "Shell": {
          "type": "string"
        },
        "ArgumentsPrefix": {
          "type": "string",
          "default": ""
        }
      },
      "required": []
    },

    "QueryparmDefaults": {
      "type": "object",
      "properties": {
        "Type": { "$ref": "#/definitions/ParameterType", "default": "string" },
        "Optional": {
          "type": "boolean",
          "default": true
        }
      },
      "required": []
    },

    "Endpoints": {
      "type": "array",
      "items": {
          "type": "object",
          "properties": {
            "RoutePrefix": {
              "type": "string"
            },
            "Id": {
              "type": "string"
            },
            "Route": {
              "type": "string"
            },
            "Actions": {
              "type": "array",
              "items":
                {
                  "type": "object",
                  "properties": {
                    "Method": {
                      "type": "string"
                    },
                    "Type": {
                      "type": "string"
                    },
                    "Shell": {
                      "type": "string"
                    },
                    "ArgumentsPrefix": {
                      "type": "string"
                    },
                    "CommandLine": {
                      "type": "string"
                    },
                    "Parms": {
                      "type": "array",
                      "items": { "$ref": "#/definitions/QueryParameter" }
                    },
                    "ContentType": {
                      "type": "string"
                    },
                    "DownloadFileName": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "Method",
                    "CommandLine"
                  ]
                }
            }
          },
          "required": [
            "Id"
          ]
        }
    }
  },
  "required": [
    "EndPointDefaults",
    "ActionDefaults",
    "QueryparmDefaults",
    "Endpoints"
  ]
}

=== gitmala/AnyRestDotNet/AnyRest/config.json
{
	"EndPointDefaults":  { "RoutePrefix":  "api/v1/" },

	"ActionDefaults":  { "Shell": "cmd.exe", "ArgumentsPrefix":  "/c " },

	"QueryparmDefaults":  { "Type":  "string" },

	"Endpoints":
	[
		{ "Id":  "test", "Route": "api1/file" },

		{ "Id": "MyEndPoint1", "Route": "api1/file", "Actions":
			[
				{ "Method": "GET", "Type": "command", "CommandLine": "type %AnyRESTQueryParm_filename%", "Parms": [ { "Name":"filename", "Type":"string"} ] },
				{ "Method": "POST", "Type": "command", "CommandLine": "anyRest.exe -io > %AnyRESTQueryParm_filename%", "Parms": [ { "Name":"filename", "Type":"string"} ] }
			]
		},

		{ "Id": "MyEndPoint1.1", "Route": "api1/file2/{filename}", "Actions":
			[
				{ "Method": "GET", "Type": "command", "CommandLine": "type %AnyRESTQueryParm_filename%", "Parms": [ { "Name":"filename", "Type":"string", "Optional": false } ] }
			]
		},

		{ "Id": "Env", "Route": "api1/env/{foo}/test/{bar}", "Actions":
			[
				{ "Method": "GET", "Type": "stream", "CommandLine": "set AnyREST", "Parms": [ { "Name":"foo", "Type":"string"}, { "Name":"bar", "Type":"string"} ] , "ContentType": "text/plaintext", "DownloadFileName": "filename3.jpg"}
			]
		},

		{ "Id": "MyEndPoint2", "Route": "api2/file", "Actions":
			[
				{ "Method": "GET", "Type": "stream", "CommandLine": "type %AnyRESTQueryParm_filename%", "Parms": [ { "Name":"filename", "Type":"string"} ] , "ContentType": "text/plaintext", "ReturnOnOK": "200"},
				{ "Method": "POST", "Type": "stream", "CommandLine": "anyRest.exe -io > %AnyRESTQueryParm_filename%", "Parms": [ { "Name":"filename", "Type":"string"} ], "ContentType": "text/plaintext", "ReturnOnOK": "200"}
			]
		},

		{ "Id": "MyEndPoint2", "Route": "api3/Round", "Actions":
			[
				{ "Method": "PUT", "Type": "stream", "CommandLine": "anyRest.exe -io", "Parms": [], "ContentType": "text/plaintext", "ReturnOnOK": "200"},
				{ "Method": "POST", "Type": "stream", "CommandLine": "anyRest.exe -s 5000 && anyRest.exe -io", "Parms": [], "ContentType": "text/plaintext", "ReturnOnOK": "200"}
			]
		}
	]
}
